# Title:   Configuration parameters

TEST_SIZE = 0.2
N_STEPS_IN = 1500
N_STEPS_OUT = 500
OPTIMIZER = 'adam'
LOSS_FUNCTION = 'mse'
VALIDATION_SPLIT = 0.3
VERBOSE_TYPE = 0
N_NEURONS = 100
ACTIVATION_FUNCTION = 'tanh'
N_EPOCHS = 10
