# Title:   Configuration parameters

TEST_SIZE = 0.2
N_STEPS_IN = 5
N_STEPS_OUT = 3
OPTIMIZER = 'adam'
LOSS_FUNCTION = 'mse'
VALIDATION_SPLIT = 0.3
VERBOSE_TYPE = 0
N_NEURONS = 50
ACTIVATION_FUNCTION = 'tanh'
N_EPOCHS = 5
