# Title:   Configuration parameters

TEST_SIZE = 0.2
N_STEPS_IN = 5
N_STEPS_OUT = 3
N_LAYERS = 2
N_NEURONS = 50
ACTIVATION_FUNCTION = 'tanh'
OPTIMIZER = 'adam'
LOSS_FUNCTION = 'mse'
N_EPOCHS = 5
VALIDATION_SPLIT = 0.2
VERBOSE_TYPE = 0
